### ISSUE TITLE
SyntaxError thrown on startup

### ISSUE THREAD

**Issue by lekkas** [resin-io/versionist#27]
Tried to give `versionist` a spin, I got the following error after following the README.md instructions:

```
kostasl@macbook:~/Lab/versionist$ versionist -h
/usr/local/lib/node_modules/versionist/lib/versionist.js:66
exports.readCommitHistory = (gitDirectory, options = {}, callback) => {
                                                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/versionist/bin/cli.js:30:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

By the way, unrelated to this issue, do we have an 'opinionated' i.e. standard Resin Handlebars template?

Thanks!

**Comment by jviotti** [comment]
Hi @lekkas ,

I believe the issue is that you're running an old NodeJS version (this projects uses ES6). Can you try with say, v6?

> By the way, unrelated to this issue, do we have an 'opinionated' i.e. standard Resin Handlebars template?

We don't have an opinionated template, but we should. You can check the one we use at Etcher though.

**Comment by lekkas** [comment]
You were right @jviotti , I was running`v4.3.0` , installed `v6.2.1` and works great 👍  Thanks!
